# Generated by Django 6.0 on 2026-01-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='total_posts',
        ),
    ]
