# Generated by Django 6.0 on 2026-01-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_post_comment_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
